### ISSUE TITLE
never used node 

### ISSUE THREAD

**Issue by peytonmo** [iliaamiri/a-web-bot-for-booking-the-closest-possible-appointment-on-ICBC-Driver-Licensing#10]
Hey im clueless on how to work this, when I change the name to configure.js. Should it automatically redirect me to node when I open the file? it takes me to windows script viewer.  I tried “opening with” node but it just closes automatically. or do i copy paste it to node? Thanks.

**Comment by iliaamiri** [comment]
Do you have experience working with Node.js and JavaScript?

**Comment by peytonmo** [comment]
No

**Comment by iliaamiri** [comment]
Ok. 

1. Change the `config-sample.js` to `config.js`
2. In the main folder of the project, in the command line, run `npm install`
3. You'll need to follow README.md instructions to setup the time period logic for finding the appointment.
4. And, set up the Gmail IMAP secret too. 

Ask ChatGPT or any other LLMs to clarify unknown concepts. 

I should've mentioned in the README that some knowledge of Node.js and command line basics are required as well.

**Comment by peytonmo** [comment]
So I got pretty far but now I get  SyntaxError: Unexpected token 'export' at compileSourceTextModule (node:internal/modules/esm/utils:339:16) at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:168:18) at callTranslator (node:internal/modules/esm/loader:428:14) at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:434:30) on chatgpt it says to either change it to "CommonJS syntax" or "Enable ES Module support in Node.js" Which one should I do? Thanks

**Comment by peytonmo** [comment]
> Ok. 
> 
> 
> 
> 1. Change the `config-sample.js` to `config.js`
> 
> 2. In the main folder of the project, in the command line, run `npm install`
> 
> 3. You'll need to follow README.md instructions to setup the time period logic for finding the appointment.
> 
> 4. And, set up the Gmail IMAP secret too. 
> 
> 
> 
> Ask ChatGPT or any other LLMs to clarify unknown concepts. 
> 
> 
> 
> I should've mentioned in the README that some knowledge of Node.js and command line basics are required as well.
> 
> 

Thank you so much for the help!! I finally got it working after some hard work. Appreciate you putting this out to help snag the icbc spots!!
