### ISSUE TITLE
any support documentation for MacOs

### ISSUE THREAD

**Issue by dhruvgupta1730** [iliaamiri/a-web-bot-for-booking-the-closest-possible-appointment-on-ICBC-Driver-Licensing#6]
hey would you happen to have any resources as to how to make it run on macOS ? @iliaamiri

**Comment by iliaamiri** [comment]
Node and NPM are going to work on Mac just fine.

For the Selenium server, you might have to either run a CentOS 7 on a local VM and bind the ports to your host.

OR, use docker which I think is easier. I wrote about it in the Readme on how to use Docker. Basically, you'll have to run a Docker container hosting your Selenium Server.

If you wanna get familiar with Docker itself, I'd recommend watching this video even though I know it's super long: https://www.youtube.com/watch?v=fqMOX6JJhGo&t=6039s

Everything in the README should be the same for MacOS.

**Comment by dhruvgupta1730** [comment]
Thanks for the info, setup docker and got it to run, but now it's stuck in a loop. the error it displays is 

Retrying...
Redirecting to the start-point...
ERROR: WebDriverError: Unknown error: {"additionalInformation":"Driver info: driver.version: unknown","localizedMessage":"Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: Process unexpectedly closed with status 1\nBuild info: version: '4.0.0', revision: '3a21814679'\nSystem info: host: '3e81081e5010', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.49-linuxkit', java.version: '1.8.0_311'\nDriver info: driver.version: unknown\nBuild info: version: '4.0.0', revision: '3a21814679'\nSystem info: host: '3e81081e5010', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.49-linuxkit', java.version: '1.8.0_311'\nDriver info: driver.version: unknown","systemInformation":"System info: host: '3e81081e5010', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.49-linuxkit', java.version: '1.8.0_311'","supportUrl":null,"cause":null,"stackTrace":[{"fileName":"DriverServiceSessionFactory.java","nativeMethod":false,"methodName":"apply","className":"org.openqa.selenium.grid.node.config.DriverServiceSessionFactory","lineNumber":184},{"fileName":"DriverServiceSessionFactory.java","nativeMethod":false,"methodName":"apply","className":"org.openqa.selenium.grid.node.config.DriverServiceSessionFactory","lineNumber":65},{"fileName":"SessionSlot.java","nativeMethod":false,"methodName":"apply","className":"org.openqa.selenium.grid.node.local.SessionSlot","lineNumber":143},{"fileName":"LocalNode.java","nativeMethod":false,"methodName":"newSession","className":"org.openqa.selenium.grid.node.local.LocalNode","lineNumber":315},{"fileName":"LocalDistributor.java","nativeMethod":false,"methodName":"startSession","className":"org.openqa.selenium.grid.distributor.local.LocalDistributor","lineNumber":513},{"fileName":"LocalDistributor.java","nativeMethod":false,"methodName":"newSession","className":"org.openqa.selenium.grid.distributor.local.LocalDistributor","lineNumber":440},{"fileName":"LocalDistributor.java","nativeMethod":false,"methodName":"handleNewSessionRequest","className":"org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable","lineNumber":648},{"fileName":"LocalDistributor.java","nativeMethod":false,"methodName":"lambda$run$1","className":"org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable","lineNumber":612},{"fileName":"ThreadPoolExecutor.java","nativeMethod":false,"methodName":"runWorker","className":"java.util.concurrent.ThreadPoolExecutor","lineNumber":1149},{"fileName":"ThreadPoolExecutor.java","nativeMethod":false,"methodName":"run","className":"java.util.concurrent.ThreadPoolExecutor$Worker","lineNumber":624},{"fileName":"Thread.java","nativeMethod":false,"methodName":"run","className":"java.lang.Thread","lineNumber":748}],"suppressed":[],"message":"Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: Process unexpectedly closed with status 1\nBuild info: version: '4.0.0', revision: '3a21814679'\nSystem info: host: '3e81081e5010', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.49-linuxkit', java.version: '1.8.0_311'\nDriver info: driver.version: unknown\nBuild info: version: '4.0.0', revision: '3a21814679'\nSystem info: host: '3e81081e5010', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.49-linuxkit', java.version: '1.8.0_311'\nDriver info: driver.version: unknown","rawMessage":"Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: Process unexpectedly closed with status 1\nBuild info: version: '4.0.0', revision: '3a21814679'\nSystem info: host: '3e81081e5010', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.49-linuxkit', java.version: '1.8.0_311'\nDriver info: driver.version: unknown","buildInformation":{"buildRevision":"3a21814679","releaseLabel":"4.0.0"}}

**Comment by dhruvgupta1730** [comment]
Got it working, thanks a lot man.
