### ISSUE TITLE
Error: getaddrinfo ENOTFOUND IMAP SERVER

### ISSUE THREAD

**Issue by ElaineYao** [iliaamiri/a-web-bot-for-booking-the-closest-possible-appointment-on-ICBC-Driver-Licensing#9]
Hi, 

Thanks for sharing this web-bot! I met the following problem after running `npm run start`. 

```
$ npm run start

> icbc-appointment-bot@1.0.0 start
> node src/main.js

Error: getaddrinfo ENOTFOUND IMAP SERVER
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'IMAP SERVER',
  source: 'socket'
}
{
  user: 'xxx@gmail.com',
  password: 'xxx',
  host: 'IMAP SERVER',
  port: 993,
  tls: true,
  tlsOptions: { rejectUnauthorized: false }
}
ERROR:Error: getaddrinfo ENOTFOUND IMAP SERVER
  __ ___      _ ___ 
 (_   |  /\  |_) |  
 __)  | /--\ | \ |  
                    
------------- Configs ---------------
Last Name: XXX
Driver License Number: XXX
Keyword: XXX

Interval Between Each Refresh: 1000ms
-------------------------------------
[2024-07-19, 5:41:56 p.m.] Error while trying to close survey popup:
[2024-07-19, 5:41:56 p.m.] Redirecting to the start-point...
[2024-07-19, 5:41:57 p.m.] ERROR: TypeError: this.page.$x is not a function
[2024-07-19, 5:41:57 p.m.] Retrying...

```

I think something might be wrong with the `password:` setting for Gmail. However, I did follow this [link](https://support.google.com/accounts/answer/185833) to set up the app password, which is a 16-digit randomly-generated password, and pasted it into the `password` field. 

Do you have an idea of what might be wrong? 

Thanks in advance!

**Comment by iliaamiri** [comment]
Hey! Thanks for the issue. I believe you need to set the IMAP Host to imap.google.com 

I see in your logs that it hasn't been set to the host. Just says "IMAP HOST".

Can you try this and let me know?

**Comment by ElaineYao** [comment]
Thanks for the prompt reply! I just set the IMAP host as you said. However, it seems there is still some issue. Is this setting correct? Or would you suggest using other emails like outlook as a workaround? Thanks!
```
npm run start

> icbc-appointment-bot@1.0.0 start
> node src/main.js

Error: getaddrinfo ENOTFOUND imap.google.com
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'imap.google.com',
  source: 'socket'
}
{
  user: 'xxx@gmail.com',
  password: 'xxx',
  host: 'imap.google.com',
  port: 993,
  tls: true,
  tlsOptions: { rejectUnauthorized: false }
}
ERROR:Error: getaddrinfo ENOTFOUND imap.google.com
```

**Comment by iliaamiri** [comment]
I haven't tested with anything else but Gmail.

I'll look into this. My guess is that the secure flag and tls stuff is blocking it. 

Will update

**Comment by iliaamiri** [comment]
Do you have a VPN or any proxies? 

Because I believe this is a network issue

**Comment by ElaineYao** [comment]
Hmm, I don't have any VPN or proxy. Is there a way to test it out?

**Comment by iliaamiri** [comment]
> Hmm, I don't have any VPN or proxy. Is there a way to test it out? 

Can you try running this command? 

```bash
ping imap.google.com
```

**Comment by ElaineYao** [comment]
```
$ ping imap.google.com
ping: imap.google.com: Name or service not known

```

**Comment by iliaamiri** [comment]
Can you temporarily disable your firewall?

If that didn't work, I guess try outlook or other providers. 

Overall, this is a network issue.

You can also try to disable TLS here:
https://github.com/iliaamiri/a-web-bot-for-booking-the-closest-possible-appointment-on-ICBC-Driver-Licensing/blob/main/src/libs/emailVerification.js#L11

**Comment by ElaineYao** [comment]
Thanks! I found out that the server should be, `export const imapServer = "imap.gmail.com";`. This works for me. 

However, I met another issue now,

```
> icbc-appointment-bot@1.0.0 start
> node src/main.js

result No Email
  __ ___      _ ___ 
 (_   |  /\  |_) |  
 __)  | /--\ | \ |  
                    
------------- Configs ---------------
Last Name: xx
Driver License Number: xx
Keyword: xxx

Interval Between Each Refresh: 5000ms
-------------------------------------
[2024-07-19, 9:46:26 p.m.] Error while trying to close survey popup:
[2024-07-19, 9:46:26 p.m.] Redirecting to the start-point...
[2024-07-19, 9:46:27 p.m.] ERROR: TypeError: this.page.$x is not a function
[2024-07-19, 9:46:27 p.m.] Retrying...
```

I wonder how to solve this, `ERROR: TypeError: this.page.$x is not a function`? Thanks!

**Comment by ElaineYao** [comment]
The issue is solved.

In `package.json`, I have ` "puppeteer": "^22.13.1",`, which is different from the original setting `"puppeteer": "^21.6.0"`.

This is because when I run `npm install`, it says, `npm warn deprecated puppeteer@21.11.0: < 22.6.4 is no longer supported`. It suggested that I run `npm audit fix --force` and this resulted in a different puppeteer version. And I think the type error is related to this version.

Instead of running `npm audit fix --force`, after `npm install`, I just directly run `npm run start`. And all of this works now!

**Comment by iliaamiri** [comment]
Yeah, I was just trying to see if I can reproduce this issue. 

I'd recommend using PNPM or Bun if you use Node.js regularly. And, NPM's suggestions are not reliable often. It complains a lot. 

Glad it's solved!

**Comment by ElaineYao** [comment]
I have one last question. When will the bot stop trying to book an appointment?

I selected the date range with appointments available and the bot successfully booked me one. However, it starts to fetch again and tries to rebook the appointment. This ends up with booking the appointments with a later time and date and this continues. 

I do see `break` at Line 263 and Line 289 in `webDriverHelper.js`. Why didn't the bot break out the loop after an appointment is found?

https://github.com/iliaamiri/a-web-bot-for-booking-the-closest-possible-appointment-on-ICBC-Driver-Licensing/blob/main/src/libs/webDriverHelper.js#L264

**Comment by iliaamiri** [comment]
Yeah, I just checked the code, the issue is that it breaks from several loops but it misses breaking from the outer while true loop.

If you add a line two lines after line 289 that goes like:
```js
if (foundAppointment) break;
```
It should break that loop and exit. I can't afford to test this though, unfortunately. 

(See where my cursor is at and take a glance at which line I am at the bottom right):  
![image](https://github.com/user-attachments/assets/af83ed52-9162-424b-89d6-2b8a3c18a956)

**Comment by iliaamiri** [comment]
Also, I see your refresh interval is 5000ms. I'd recommend increasing this to 8000 or 10000 (8 or 10 seconds) as ICBC throttles very quick.
![image](https://github.com/user-attachments/assets/00dc97bf-4e9a-44fb-8317-a5e9f5a09b9e)

**Comment by ElaineYao** [comment]
Thanks a lot! I've tested and it works all well! Can I update the changes regarding the discussion and submit a merge request?

**Comment by iliaamiri** [comment]
Absolutely! Please go ahead.

**Comment by peytonmo** [comment]
So I got  pretty far but now I get  ` SyntaxError: Unexpected token 'export'
    at compileSourceTextModule (node:internal/modules/esm/utils:339:16)
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:168:18)
    at callTranslator (node:internal/modules/esm/loader:428:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:434:30)` on chatgpt it says to either change it to "CommonJS syntax" or "Enable ES Module support in Node.js" Which one should I do? Thanks
